channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - pip
  - geopandas
  - folium
  - altair
  - notebook
  - vega
  - pyviz::param
  - datashader
  - pyviz::holoviews
  - pyviz::geoviews
  - pyviz::hvplot
  - bokeh::bokeh
  - pyviz::panel
  - pip:
      - jupyter-panel-proxy
